### ISSUE TITLE
Website German Version Broken

### ISSUE THREAD

**Issue by COM8** [TUM-Dev/eat-api#102]
When changing the language to German on the website, no dishes will be displayed.

This is caused by the website requesting the wrong .json file.
```
https://tum-dev.github.io/mensa-garching/2022/02.json?language=DE
```
It's missing the `eat-api` in the URL.

```
https://tum-dev.github.io/eat-api/mensa-garching/2022/02.json?language=DE
```

@Philipp000 could you have a look at this?

**Comment by Philipp000** [comment]
Apparently, the URL was absolute and not relative for the german version.
Actually, I don't fully understand why this works locally for me, but not on the production version.

Either way, it should be now correct, as the english URL also had to many "/".
Further, I also removed the language parameter, as this shouldn't be there.
