### ISSUE TITLE
Minify json

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/eat-api#109]
I noticed that the json produced is "human readable", an (additional?) minified version could save up to 75% size. Mobile apps could benefit from this.

Tests using [jj](https://github.com/tidwall/jj): 

```bash
$ cat all.json | wc --bytes
> 3614120

$ jj -i all.json -u | wc --bytes
> 923447
```

Even adjusting for gzip this could save about 50%:

```bash
$ cat all.json | gzip -f | wc --bytes
> 107019

$ jj -i all.json -u | gzip -f | wc --bytes
> 50856
```

**Comment by COM8** [comment]
Agree. This is a good idea.
