### ISSUE TITLE
Add Mensa Straubing

### ISSUE THREAD

**Issue by Philipp000** [TUM-Dev/eat-api#138]
The mensa straubing has menus available on the website: https://www.stwno.de/de/gastronomie/speiseplan/tum-straubing

I would propose to add an additional parser for csv-files.
The csv-files are available on urls like: https://www.stwno.de/infomax/daten-extern/csv/HS-SR/14.csv?t=1649272666
Here, it is possible to get menu data for different weeks by changing the "14" to the desired week.

I could work on this in the following days

**Comment by COM8** [comment]
Sure, this would be awesome!
