### ISSUE TITLE
`StuCafé in der Mensa Garching` not parsed

### ISSUE THREAD

**Issue by CommanderStorm** [TUM-Dev/eat-api#161]
Since some time, the StuCafé in der Mensa Garching (https://tum-dev.github.io/eat-api/#!/en/stucafe-garching) has stopped showing values. I am assuming, that something broke here, but do not have the time to investigate further at the moment.
The plan is available at https://www.studentenwerk-muenchen.de/mensa/speiseplan/speiseplan_524_-de.html

**Comment by COM8** [comment]
Thanks for reporting!

**Comment by COM8** [comment]
Turns out, there are just no new dishes available. The last available dishes are for the `08.07.2022`. So, there is nothing we can do here,
