### ISSUE TITLE
API stopped working for data in 2023

### ISSUE THREAD

**Issue by allesklardy** [TUM-Dev/eat-api#180]
I have a Mastodon bot running on https://tum.social/@mensabot that retrieves the current menu. However, today I noticed that the bot stopped working. On closer inspection, I found that the API is returning only 404 errors for this and the next few weeks. The human-readable website is also not working as it requires the api.

**Comment by COM8** [comment]
@allesklardy thanks for reporting!

I stumbled across this as well and up until today there wasn't any up to date data available from the Studentenwerk.

Since the CI runs only once every day, dishes should be available again starting from tomorrow.
