### ISSUE TITLE
Setup Daily builds on Travis

### ISSUE THREAD

**Issue by jpbernius** [TUM-Dev/eat-api#2]
In the `srehwald/eat-api` repo, we used Travis CI to keep `gh-pages` up to date.
We need to configure Travis for this repo as well.

**Comment by COM8** [comment]
I will have a look at this.

**Comment by COM8** [comment]
I don't have access to it.
Neither to the GitHub Pages stuff nor to the Travis stuff.
So somebody else with more power needs to do this.

**Comment by jpbernius** [comment]
Yes, I think this required admin permissions.

**Comment by jpbernius** [comment]
We can switch to @actions once it hits general availability on November 13th.

**Comment by COM8** [comment]
Yes, we should switch to it.
