### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by lukasdenk** [TUM-Dev/eat-api#47]
The `README` contains some old parts. E.g., it announces a change which _will_ happen in _2020_. 
If you recognize other parts to update, please leave a comment.

**Comment by COM8** [comment]
Yes, I agree. The README.m could be updated a bit like removing the "will happen in 2020" and fixing the example.

**Comment by COM8** [comment]
Closing this for now in favor of #98.
As soon as we got the documentation for the API endpoint up and running we declutter the README.md even more.
