### ISSUE TITLE
Replace moment.js

### ISSUE THREAD

**Issue by Garfield96** [TUM-Dev/eat-api#50]
The currently used version (2.19.4) of moment.js is outdated. Since moment.js reached its EOL (see [https://momentjs.com/docs/#/-project-status/](https://momentjs.com/docs/#/-project-status/)) it should be replaced.

**Comment by Philipp000** [comment]
I checked the usages of moment.js in the gh-pages branch, and I think, the best variant is to replace it with the Native version of the Date API.
They also state in their documents, that this shouldn't be a big problem ([https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md#string--date-format](https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md#string--date-format)).

I can work on this, and create a pull request.

**Comment by Philipp000** [comment]
This issue should be closed now.

Shouldn't this happen automatically, or do I have to do something else, for it to close automatically, when the PR gets merged?

**Comment by COM8** [comment]
There was no PR linked with this issue.
