### ISSUE TITLE
Website broken in Safari

### ISSUE THREAD

**Issue by COM8** [TUM-Dev/eat-api#63]
The Website is rather broken in Safari.
I'm using it on i(Pad)OS 15.1 and I can't get it to show dishes reliably any more.
The following Link produces the following result on my iPhone and iPad:
https://tum-dev.github.io/eat-api/#!/mensa-garching
![eat-api](https://user-images.githubusercontent.com/11741404/143613401-d8bd5452-95d3-4af4-baef-9998c0266df8.png)
![IMG_0236](https://user-images.githubusercontent.com/11741404/143613429-de3ec4fe-d3eb-4b49-90ff-0c4f391ced27.PNG)

When changing the date, the following happens:
![IMG_0237](https://user-images.githubusercontent.com/11741404/143613499-93c9bf8a-a37c-4e03-a2fd-889c83a8ffd9.PNG)

Perhaps we should forward all invalid dates/URLs to the default page for the canteen/eat-api?

Also I'm unable to close the canteen selection on my iPad. I can see the small cross in the top right corner, but it does not work. Also tapping anywhere else does not work.
![IMG_0235](https://user-images.githubusercontent.com/11741404/143613668-a5b592de-7fcf-4dc6-8885-e26fed488210.PNG)

**Comment by COM8** [comment]
Ping @Philipp000

**Comment by Philipp000** [comment]
The problems with the invalid URL and the iPad browser in general should be fixed with #61 
I will take a look at the closing of the popup in the coming days.

**Comment by Philipp000** [comment]
I have tested the map closing on my iPad and several other touch devices, however I couldn‘t reproduce the error.
Is there anything else you did, before trying to close the modal?
Also, the problem only occurs on your iPad?

**Comment by COM8** [comment]
Works now 🤷‍♂️.
But we should increase the contrast of the X in dark mode. It's rather hard to see.

**Comment by COM8** [comment]
Everything else is working now on my iPad. I'd say this has been some kind of cashing or publishing issue...
