### ISSUE TITLE
GH-Pages - Issues with symbols in canteen_id: stubistro-großhadern

### ISSUE THREAD

**Issue by Philipp000** [TUM-Dev/eat-api#68]
When working with the gh-pages branch, I often have issues regarding file changes, concerning the `stubistro-großhadern`.

![image](https://user-images.githubusercontent.com/1690395/144835459-eafd4ee6-8a0f-4950-a626-e566a26f5f91.png)
Git status shows this, even when I haven't made any changes.

I figured, this is probably because we have a folder for `stubistro-grosshadern` and `stubistro-großhadern`.
Since one week, the one with `ß` is updated, but before it was the one with `ss`.

I would propose, to use only the one with `ss` and move all the files from the other folder into this one. 
This should facilitate usage with different systems.

**Comment by COM8** [comment]
Agree. But then we have to rename all occurrences with the other so it is consistent.

**Comment by lukasdenk** [comment]
I actually changed this in #60.

**Comment by Philipp000** [comment]
So, we should change it in the `gh-pages` branch, once #60 is merged.
However, I tried to do that, but my os (macOS) seems to automatically merge these folders -> the `ß` is automatically converted into `ss` and there these strange conflicts come from.

So ideally this change could be done by someone on a linux system, as I suppose, there isn't this strange behavior.

**Comment by Philipp000** [comment]
For me this issue is still present in the `en/` subdirectory.

![image](https://user-images.githubusercontent.com/1690395/146752388-6d6e0d43-2af4-4fbb-b30b-c6a1f099e101.png)

**Comment by COM8** [comment]
Fixed. Thanks!
