### ISSUE TITLE
Website broken with the switch to the new labels enums

### ISSUE THREAD

**Issue by COM8** [TUM-Dev/eat-api#79]
![grafik](https://user-images.githubusercontent.com/11741404/146653818-ce5eb273-0812-4c87-b49d-ffb69341d048.png)

There are multiple problems:
* The location for the `canteens.json` changed from `https://tum-dev.github.io/eat-api/canteens.json` to `https://tum-dev.github.io/eat-api/enums/canteens.json`
* The website still uses the old ingredients instead of the new labels introduced by #60 

@Philipp000 or @lukasdenk could one of you have a look at this please?

**Comment by Philipp000** [comment]
I will work on this
