### ISSUE TITLE
Extend labels with an emoji and optionally also a short version

### ISSUE THREAD

**Issue by Philipp000** [TUM-Dev/eat-api#81]
In the eat-api Website and the Apps, there were defined lists for the ingredients with custom emojis, to display instead of the longer names.
I would propose to add these to the `labels.json` as well, to save the doubled amount of work, oposed to handle these lists in every application by itself.

Further, I would also propose to add a short version, abbreviation or something for labels, where there exists no emoji. As it would be easier to display these, instead of the enum Labels. Example: `BAVARIA` can be `GQB`.

**Comment by COM8** [comment]
I agree with you in both points.
