### ISSUE TITLE
Add opening hours to canteens

### ISSUE THREAD

**Issue by Philipp000** [TUM-Dev/eat-api#89]
We now have additional information, such as locations and with #88 also an API for the queue length.

I think it would be great to also have the opening hours included in the API.
I think a general time table, with the opening hours from this webpage: https://www.studentenwerk-muenchen.de/mensa/standorte-und-oeffnungszeiten/garching/ would be sufficient.

Of course, one could also add custom opening hours for special days (holiday, christmas, ...), but I think having the basic information is sufficient for the beginning.

What do you think about this addition?

**Comment by COM8** [comment]
Yes, this sounds nice since for example the android app shows hard coded opening hours for canteens already.

**Comment by Philipp000** [comment]
Okay, I will look into that app, and work on implementing something similar here.
